#include "test.h"
#include "string.h"
#define BUFFERSZ	1024
#define IFILE		"input.txt"
#define OFILE		"output.txt"
char usage[] = {
	"Simple lexical analyzer generator generated by dlex.\n\n"
		"usage:\n\n"
		"\tmain\t\t\tIFILE OFILE|stdout [-s]\n\n"
		"parameters:\n\n"
		"\tIFILE\t\t\tspecify the input file.\n\n"
		"\tOFILE|stdout\t\tspecify the output file or output to stdout.\n\n"
		"\t-s\t\t\tshow dlim, acceptlength and typename.\n\n"
		"Also for experiment use.\n"
};
int showDlim = 0;
char wordBuffer[BUFFERSZ],
	 ifileBuffer[BUFFERSZ];
void argvCheck(int argc, char *argv[]) {
	if (3 <= argc && argc <= 4) {
		iFile = fopen(argv[1], "rt");
		if (!iFile) {
			puts("Input file can't be opened.");
			exit(1);
		}
		if (strcmp(argv[2], "stdout")) {
			oFile = fopen(argv[2], "wt");
		} else {
			oFile = stdout;
		}
		if (3 < argc && !strcmp(argv[3], "-s")) {
			showDlim = 1;
		}
	} else {
		puts(usage);
		exit(2);
	}
}
void getWordBuffer() {
	int i;
	for (i = 0; i < acceptLength; i++) {
		wordBuffer[i] = fgetc(iFile);
	}
	wordBuffer[i] = 0;
}
void escaper() {
	char tmp[BUFFERSZ] = "", *i = wordBuffer;
	for ( ; *i; i++) {
		char symbol[5];
		escape(symbol, *i);
		strcat(tmp, symbol);
	}
	strcpy(wordBuffer, tmp);
}
int main(int argc, char *argv[]) {
#if DEBUG
	int i;
	puts("symbol table:");
	for (i = 0; i < 127; i++) {
		printf("%d: %c\n", i, i);
	}
	iFile = fopen(IFILE, "rt");
	oFile = fopen(OFILE, "wt");
	printf("this is a test\n");
#else
	argvCheck(argc, argv);
#endif
	for ( ; !isEOF; ) {
		int i, c;
		NFA();
		getWordBuffer();
		if (!acceptLength) {
			puts("invail symbols.\n");
			exit(1);
		}
		escaper();
		int id = dealAction(acceptState);
		if (showDlim) {
			fprintf(oFile, "%4d: [-- %20s, %20s --]\n",
					acceptLength, typeName[id], wordBuffer);
		} else {
			if (id != dlim) {
				fprintf(oFile, "[-- %20d, %20s --]\n", id, wordBuffer);
			}
		}
		if (id == term) {
			break;
		}
	}
	close(iFile);
	close(oFile);
	return 0;
}
